# Generated by Django 5.1 on 2024-08-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("vatpercentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
